name: Set up the project
inputs:
  os:
    description: OS version to use
    required: true
    default: ubuntu-latest
  php:
    description: PHP version to use
    required: true
    default: '8.1'
  coverage:
    description: Coverage tool to use
    required: true
    default: none
runs:
  using: composite
  steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        coverage: ${{ inputs.coverage }}

    - name: Determine Composer cache directory on Linux
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

    - name: Determine Composer cache directory on Windows
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: |
        $cacheDir = (composer config cache-dir)
        echo "COMPOSER_CACHE_DIR=$cacheDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Determine Composer cache directory on Linux
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

    - name: Determine Composer cache directory on Windows
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

    - name: Cache dependencies installed with Composer
      uses: actions/cache@v5
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: php${{ inputs.php }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          php${{ inputs.php }}-composer-

    - name: Update Composer on Linux
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: composer self-update

    - name: Update Composer on Windows
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: composer self-update

    - name: Install dependencies on Linux
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

    - name: Install dependencies on Windows
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
